"""initial schema

Revision ID: 69c4151aa633
Revises: 
Create Date: 2026-09-13 14:31:41.339134
"""
from __future__ import annotations

from alembic import op
import sqlalchemy as sa


revision = '69c4151aa633'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:# ### commands auto generated by Alembic - please adjust! ###
    # FTS5-индекс поиска (unicode61). При отсутствии FTS5 поиск работает по fallback-таблице.
    bind = op.get_bind()
    has_fts = bind.exec_driver_sql("SELECT sqlite_compileoption_used('ENABLE_FTS5')").scalar()
    if has_fts:
        bind.exec_driver_sql(
            "CREATE VIRTUAL TABLE search_fts USING fts5"
            "(text, set_id UNINDEXED, card_id UNINDEXED, tokenize='unicode61')"
        )
    op.create_table('server_settings',
    sa.Column('key', sa.String(length=64), nullable=False),
    sa.Column('value_json', sa.Text(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('key')
    )
    op.create_table('users',
    sa.Column('username', sa.String(length=64), nullable=False),
    sa.Column('username_normalized', sa.String(length=64), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('role', sa.String(length=16), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('preferred_locale', sa.String(length=8), nullable=False),
    sa.Column('timezone', sa.String(length=64), nullable=False),
    sa.Column('theme', sa.String(length=16), nullable=False),
    sa.Column('last_login_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_username_normalized'), ['username_normalized'], unique=True)

    op.create_table('activity_events',
    sa.Column('user_id', sa.String(length=32), nullable=False),
    sa.Column('event_type', sa.String(length=32), nullable=False),
    sa.Column('occurred_at_utc', sa.DateTime(), nullable=False),
    sa.Column('local_date', sa.String(length=10), nullable=False),
    sa.Column('set_id', sa.String(length=32), nullable=True),
    sa.Column('card_id', sa.String(length=32), nullable=True),
    sa.Column('dedupe_key', sa.String(length=80), nullable=True),
    sa.Column('meta_json', sa.Text(), nullable=False),
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('activity_events', schema=None) as batch_op:
        batch_op.create_index('ix_activity_user_date', ['user_id', 'local_date'], unique=False)
        batch_op.create_index('ix_activity_user_time', ['user_id', 'occurred_at_utc'], unique=False)

    op.create_table('audit_events',
    sa.Column('actor_id', sa.String(length=32), nullable=True),
    sa.Column('action', sa.String(length=64), nullable=False),
    sa.Column('target_type', sa.String(length=32), nullable=True),
    sa.Column('target_id', sa.String(length=64), nullable=True),
    sa.Column('result', sa.String(length=16), nullable=False),
    sa.Column('details_json', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.ForeignKeyConstraint(['actor_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('audit_events', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_audit_events_action'), ['action'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_events_created_at'), ['created_at'], unique=False)

    op.create_table('daily_goals',
    sa.Column('user_id', sa.String(length=32), nullable=False),
    sa.Column('local_date', sa.String(length=10), nullable=False),
    sa.Column('timezone_at_creation', sa.String(length=64), nullable=False),
    sa.Column('target_reviews', sa.Integer(), nullable=False),
    sa.Column('target_minutes', sa.Integer(), nullable=False),
    sa.Column('target_new_cards', sa.Integer(), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'local_date', name='uq_daily_goal')
    )
    op.create_table('folders',
    sa.Column('user_id', sa.String(length=32), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'name', name='uq_folder_user_name')
    )
    op.create_table('match_records',
    sa.Column('user_id', sa.String(length=32), nullable=False),
    sa.Column('source_fingerprint', sa.String(length=64), nullable=False),
    sa.Column('direction', sa.String(length=16), nullable=False),
    sa.Column('board_size', sa.Integer(), nullable=False),
    sa.Column('penalty_rule', sa.String(length=32), nullable=False),
    sa.Column('elapsed_ms', sa.Integer(), nullable=False),
    sa.Column('mistakes', sa.Integer(), nullable=False),
    sa.Column('penalty_ms', sa.Integer(), nullable=False),
    sa.Column('final_ms', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('match_records', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_match_records_user_id'), ['user_id'], unique=False)

    op.create_table('media',
    sa.Column('owner_id', sa.String(length=32), nullable=False),
    sa.Column('storage_key', sa.String(length=200), nullable=False),
    sa.Column('original_name', sa.String(length=255), nullable=False),
    sa.Column('media_type', sa.String(length=16), nullable=False),
    sa.Column('mime_type', sa.String(length=64), nullable=False),
    sa.Column('byte_size', sa.Integer(), nullable=False),
    sa.Column('sha256', sa.String(length=64), nullable=False),
    sa.Column('width', sa.Integer(), nullable=True),
    sa.Column('height', sa.Integer(), nullable=True),
    sa.Column('duration_ms', sa.Integer(), nullable=True),
    sa.Column('description', sa.String(length=500), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('storage_key')
    )
    with op.batch_alter_table('media', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_media_owner_id'), ['owner_id'], unique=False)

    op.create_table('sessions',
    sa.Column('user_id', sa.String(length=32), nullable=True),
    sa.Column('kind', sa.String(length=16), nullable=False),
    sa.Column('token_hash', sa.String(length=64), nullable=False),
    sa.Column('csrf_hash', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('last_seen_at', sa.DateTime(), nullable=False),
    sa.Column('revoked_at', sa.DateTime(), nullable=True),
    sa.Column('user_agent', sa.String(length=300), nullable=True),
    sa.Column('ip', sa.String(length=64), nullable=True),
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('sessions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_sessions_expires_at'), ['expires_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_sessions_token_hash'), ['token_hash'], unique=True)
        batch_op.create_index(batch_op.f('ix_sessions_user_id'), ['user_id'], unique=False)

    op.create_table('sets',
    sa.Column('owner_id', sa.String(length=32), nullable=False),
    sa.Column('title', sa.String(length=300), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('front_language', sa.String(length=16), nullable=False),
    sa.Column('back_language', sa.String(length=16), nullable=False),
    sa.Column('visibility', sa.String(length=16), nullable=False),
    sa.Column('archived', sa.Boolean(), nullable=False),
    sa.Column('archived_at', sa.DateTime(), nullable=True),
    sa.Column('content_version', sa.Integer(), nullable=False),
    sa.Column('share_revision', sa.Integer(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('sets', schema=None) as batch_op:
        batch_op.create_index('ix_sets_archived', ['archived'], unique=False)
        batch_op.create_index('ix_sets_owner_updated', ['owner_id', 'updated_at'], unique=False)
        batch_op.create_index('ix_sets_visibility_updated', ['visibility', 'updated_at'], unique=False)

    op.create_table('srs_settings',
    sa.Column('user_id', sa.String(length=32), nullable=False),
    sa.Column('desired_retention', sa.Float(), nullable=False),
    sa.Column('new_per_day', sa.Integer(), nullable=False),
    sa.Column('round_size', sa.Integer(), nullable=False),
    sa.Column('config_version', sa.Integer(), nullable=False),
    sa.Column('params_json', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.create_table('study_sessions',
    sa.Column('user_id', sa.String(length=32), nullable=False),
    sa.Column('mode', sa.String(length=16), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('settings_json', sa.Text(), nullable=False),
    sa.Column('sources_json', sa.Text(), nullable=False),
    sa.Column('seed', sa.Integer(), nullable=False),
    sa.Column('state_json', sa.Text(), nullable=False),
    sa.Column('pool_json', sa.Text(), nullable=False),
    sa.Column('current_index', sa.Integer(), nullable=False),
    sa.Column('active_ms', sa.Integer(), nullable=False),
    sa.Column('deadline_at', sa.DateTime(), nullable=True),
    sa.Column('result_json', sa.Text(), nullable=True),
    sa.Column('started_at', sa.DateTime(), nullable=False),
    sa.Column('last_activity_at', sa.DateTime(), nullable=False),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('study_sessions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_study_sessions_last_activity_at'), ['last_activity_at'], unique=False)
        batch_op.create_index('ix_study_sessions_user_status', ['user_id', 'status', 'last_activity_at'], unique=False)

    op.create_table('tags',
    sa.Column('owner_id', sa.String(length=32), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('name_normalized', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('owner_id', 'name_normalized', name='uq_tag_owner_name')
    )
    op.create_table('user_preferences',
    sa.Column('user_id', sa.String(length=32), nullable=False),
    sa.Column('daily_goal_reviews', sa.Integer(), nullable=False),
    sa.Column('daily_goal_minutes', sa.Integer(), nullable=False),
    sa.Column('daily_goal_new_cards', sa.Integer(), nullable=False),
    sa.Column('goals_enabled', sa.Boolean(), nullable=False),
    sa.Column('streak_enabled', sa.Boolean(), nullable=False),
    sa.Column('sound_enabled', sa.Boolean(), nullable=False),
    sa.Column('autoplay_audio', sa.Boolean(), nullable=False),
    sa.Column('volume', sa.Float(), nullable=False),
    sa.Column('tts_rate', sa.Float(), nullable=False),
    sa.Column('prefer_local_voices', sa.Boolean(), nullable=False),
    sa.Column('allow_network_voices', sa.Boolean(), nullable=False),
    sa.Column('default_direction', sa.String(length=16), nullable=False),
    sa.Column('normalization_policy', sa.String(length=16), nullable=False),
    sa.Column('font_scale', sa.Float(), nullable=False),
    sa.Column('reduced_motion', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.create_table('cards',
    sa.Column('set_id', sa.String(length=32), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('content_version', sa.Integer(), nullable=False),
    sa.Column('front_text', sa.Text(), nullable=False),
    sa.Column('back_text', sa.Text(), nullable=False),
    sa.Column('front_context', sa.Text(), nullable=False),
    sa.Column('back_context', sa.Text(), nullable=False),
    sa.Column('front_hint', sa.Text(), nullable=False),
    sa.Column('back_hint', sa.Text(), nullable=False),
    sa.Column('front_explanation', sa.Text(), nullable=False),
    sa.Column('back_explanation', sa.Text(), nullable=False),
    sa.Column('front_example', sa.Text(), nullable=False),
    sa.Column('back_example', sa.Text(), nullable=False),
    sa.Column('front_language', sa.String(length=16), nullable=True),
    sa.Column('back_language', sa.String(length=16), nullable=True),
    sa.Column('enabled_front_to_back', sa.Boolean(), nullable=False),
    sa.Column('enabled_back_to_front', sa.Boolean(), nullable=False),
    sa.Column('written_check_front', sa.Boolean(), nullable=False),
    sa.Column('written_check_back', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.ForeignKeyConstraint(['set_id'], ['sets.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('cards', schema=None) as batch_op:
        batch_op.create_index('ix_cards_set_position', ['set_id', 'position'], unique=False)

    op.create_table('folder_sets',
    sa.Column('folder_id', sa.String(length=32), nullable=False),
    sa.Column('set_id', sa.String(length=32), nullable=False),
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.ForeignKeyConstraint(['folder_id'], ['folders.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['set_id'], ['sets.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('folder_id', 'set_id', name='uq_folder_set')
    )
    with op.batch_alter_table('folder_sets', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_folder_sets_folder_id'), ['folder_id'], unique=False)

    op.create_table('import_jobs',
    sa.Column('user_id', sa.String(length=32), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('source_format', sa.String(length=16), nullable=False),
    sa.Column('target_set_id', sa.String(length=32), nullable=True),
    sa.Column('create_new_set', sa.Boolean(), nullable=False),
    sa.Column('new_set_title', sa.String(length=300), nullable=True),
    sa.Column('duplicate_policy', sa.String(length=16), nullable=False),
    sa.Column('expected_content_version', sa.Integer(), nullable=True),
    sa.Column('fingerprint', sa.String(length=64), nullable=True),
    sa.Column('preview_json', sa.Text(), nullable=False),
    sa.Column('staging_json', sa.Text(), nullable=False),
    sa.Column('errors_json', sa.Text(), nullable=False),
    sa.Column('progress', sa.Integer(), nullable=False),
    sa.Column('applied_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('finished_at', sa.DateTime(), nullable=True),
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.ForeignKeyConstraint(['target_set_id'], ['sets.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('import_jobs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_import_jobs_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_import_jobs_user_id'), ['user_id'], unique=False)

    op.create_table('library_entries',
    sa.Column('user_id', sa.String(length=32), nullable=False),
    sa.Column('set_id', sa.String(length=32), nullable=False),
    sa.Column('is_favorite', sa.Boolean(), nullable=False),
    sa.Column('saved_at', sa.DateTime(), nullable=False),
    sa.Column('last_studied_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.ForeignKeyConstraint(['set_id'], ['sets.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'set_id', name='uq_library_user_set')
    )
    with op.batch_alter_table('library_entries', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_library_entries_user_id'), ['user_id'], unique=False)

    op.create_table('search_fallback',
    sa.Column('set_id', sa.String(length=32), nullable=False),
    sa.Column('normalized_text', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['set_id'], ['sets.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('set_id'),
    sa.UniqueConstraint('set_id', name='uq_search_fallback_set')
    )
    op.create_table('set_tags',
    sa.Column('set_id', sa.String(length=32), nullable=False),
    sa.Column('tag_id', sa.String(length=32), nullable=False),
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.ForeignKeyConstraint(['set_id'], ['sets.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tag_id'], ['tags.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('set_id', 'tag_id', name='uq_set_tag')
    )
    with op.batch_alter_table('set_tags', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_set_tags_set_id'), ['set_id'], unique=False)

    op.create_table('share_links',
    sa.Column('set_id', sa.String(length=32), nullable=False),
    sa.Column('token_hash', sa.String(length=64), nullable=False),
    sa.Column('created_by', sa.String(length=32), nullable=False),
    sa.Column('revision', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=True),
    sa.Column('revoked_at', sa.DateTime(), nullable=True),
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['set_id'], ['sets.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('token_hash')
    )
    with op.batch_alter_table('share_links', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_share_links_set_id'), ['set_id'], unique=False)

    op.create_table('snapshot_media',
    sa.Column('study_session_id', sa.String(length=32), nullable=False),
    sa.Column('media_id', sa.String(length=32), nullable=False),
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.ForeignKeyConstraint(['media_id'], ['media.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['study_session_id'], ['study_sessions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('study_session_id', 'media_id', name='uq_snapshot_media')
    )
    with op.batch_alter_table('snapshot_media', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_snapshot_media_study_session_id'), ['study_session_id'], unique=False)

    op.create_table('srs_enrollments',
    sa.Column('user_id', sa.String(length=32), nullable=False),
    sa.Column('set_id', sa.String(length=32), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('forward_enabled', sa.Boolean(), nullable=False),
    sa.Column('reverse_enabled', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.ForeignKeyConstraint(['set_id'], ['sets.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'set_id', name='uq_srs_enrollment')
    )
    with op.batch_alter_table('srs_enrollments', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_srs_enrollments_user_id'), ['user_id'], unique=False)

    op.create_table('study_session_items',
    sa.Column('session_id', sa.String(length=32), nullable=False),
    sa.Column('item_uid', sa.String(length=32), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('card_id', sa.String(length=32), nullable=False),
    sa.Column('direction', sa.String(length=16), nullable=False),
    sa.Column('content_version', sa.Integer(), nullable=False),
    sa.Column('task_type', sa.String(length=24), nullable=False),
    sa.Column('snapshot_json', sa.Text(), nullable=False),
    sa.Column('choices_json', sa.Text(), nullable=True),
    sa.Column('answer_key_json', sa.Text(), nullable=True),
    sa.Column('draft_answer', sa.Text(), nullable=True),
    sa.Column('draft_version', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('skipped', sa.Boolean(), nullable=False),
    sa.Column('revealed', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['study_sessions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('session_id', 'item_uid', name='uq_session_item_uid')
    )
    with op.batch_alter_table('study_session_items', schema=None) as batch_op:
        batch_op.create_index('ix_items_session_pos', ['session_id', 'position'], unique=False)

    op.create_table('test_attempts',
    sa.Column('user_id', sa.String(length=32), nullable=False),
    sa.Column('session_id', sa.String(length=32), nullable=False),
    sa.Column('score', sa.Integer(), nullable=False),
    sa.Column('max_score', sa.Integer(), nullable=False),
    sa.Column('adjusted_score', sa.Integer(), nullable=True),
    sa.Column('detail_json', sa.Text(), nullable=False),
    sa.Column('finished_at', sa.DateTime(), nullable=False),
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['study_sessions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('session_id', name='uq_test_attempt_session')
    )
    with op.batch_alter_table('test_attempts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_test_attempts_user_id'), ['user_id'], unique=False)

    op.create_table('accepted_answers',
    sa.Column('card_id', sa.String(length=32), nullable=False),
    sa.Column('side', sa.String(length=8), nullable=False),
    sa.Column('answer', sa.Text(), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.ForeignKeyConstraint(['card_id'], ['cards.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('card_id', 'side', 'answer', name='uq_accepted_answer')
    )
    with op.batch_alter_table('accepted_answers', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_accepted_answers_card_id'), ['card_id'], unique=False)

    op.create_table('card_media',
    sa.Column('card_id', sa.String(length=32), nullable=False),
    sa.Column('side', sa.String(length=8), nullable=False),
    sa.Column('media_id', sa.String(length=32), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.ForeignKeyConstraint(['card_id'], ['cards.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['media_id'], ['media.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('card_id', 'side', 'media_id', name='uq_card_media')
    )
    with op.batch_alter_table('card_media', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_card_media_card_id'), ['card_id'], unique=False)

    op.create_table('set_permissions',
    sa.Column('set_id', sa.String(length=32), nullable=False),
    sa.Column('user_id', sa.String(length=32), nullable=False),
    sa.Column('permission', sa.String(length=16), nullable=False),
    sa.Column('source', sa.String(length=16), nullable=False),
    sa.Column('share_link_id', sa.String(length=32), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('revoked_at', sa.DateTime(), nullable=True),
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.ForeignKeyConstraint(['set_id'], ['sets.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['share_link_id'], ['share_links.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('set_id', 'user_id', 'source', 'share_link_id', name='uq_set_permission')
    )
    with op.batch_alter_table('set_permissions', schema=None) as batch_op:
        batch_op.create_index('ix_set_permissions_user_set', ['user_id', 'set_id'], unique=False)

    op.create_table('srs_states',
    sa.Column('user_id', sa.String(length=32), nullable=False),
    sa.Column('card_id', sa.String(length=32), nullable=False),
    sa.Column('direction', sa.String(length=16), nullable=False),
    sa.Column('algorithm_name', sa.String(length=32), nullable=False),
    sa.Column('algorithm_version', sa.String(length=32), nullable=False),
    sa.Column('scheduler_payload', sa.Text(), nullable=False),
    sa.Column('due_at', sa.DateTime(), nullable=False),
    sa.Column('last_review_at', sa.DateTime(), nullable=True),
    sa.Column('state_name', sa.String(length=16), nullable=False),
    sa.Column('suspended', sa.Boolean(), nullable=False),
    sa.Column('last_reviewed_content_version', sa.Integer(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('learning_epoch', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.ForeignKeyConstraint(['card_id'], ['cards.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'card_id', 'direction', name='uq_srs_state')
    )
    with op.batch_alter_table('srs_states', schema=None) as batch_op:
        batch_op.create_index('ix_srs_states_queue', ['user_id', 'suspended', 'due_at'], unique=False)

    op.create_table('study_answers',
    sa.Column('session_id', sa.String(length=32), nullable=False),
    sa.Column('item_id', sa.String(length=32), nullable=False),
    sa.Column('user_id', sa.String(length=32), nullable=False),
    sa.Column('client_event_id', sa.String(length=64), nullable=False),
    sa.Column('attempt_no', sa.Integer(), nullable=False),
    sa.Column('raw_answer', sa.Text(), nullable=True),
    sa.Column('normalized_answer', sa.Text(), nullable=True),
    sa.Column('machine_correct', sa.Boolean(), nullable=True),
    sa.Column('final_correct', sa.Boolean(), nullable=True),
    sa.Column('assisted', sa.Boolean(), nullable=False),
    sa.Column('answer_type', sa.String(length=24), nullable=False),
    sa.Column('latency_ms', sa.Integer(), nullable=True),
    sa.Column('fingerprint', sa.String(length=64), nullable=False),
    sa.Column('correction_of_id', sa.String(length=32), nullable=True),
    sa.Column('answered_at', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.ForeignKeyConstraint(['correction_of_id'], ['study_answers.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['item_id'], ['study_session_items.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['session_id'], ['study_sessions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('session_id', 'item_id', 'attempt_no', name='uq_answer_attempt'),
    sa.UniqueConstraint('user_id', 'client_event_id', name='uq_answer_client_event')
    )
    with op.batch_alter_table('study_answers', schema=None) as batch_op:
        batch_op.create_index('ix_study_answers_session', ['session_id'], unique=False)

    op.create_table('user_card_flags',
    sa.Column('user_id', sa.String(length=32), nullable=False),
    sa.Column('card_id', sa.String(length=32), nullable=False),
    sa.Column('is_starred', sa.Boolean(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.ForeignKeyConstraint(['card_id'], ['cards.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'card_id', name='uq_card_flag')
    )
    with op.batch_alter_table('user_card_flags', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user_card_flags_user_id'), ['user_id'], unique=False)

    op.create_table('srs_reviews',
    sa.Column('user_id', sa.String(length=32), nullable=False),
    sa.Column('card_id', sa.String(length=32), nullable=False),
    sa.Column('direction', sa.String(length=16), nullable=False),
    sa.Column('srs_state_id', sa.String(length=32), nullable=False),
    sa.Column('rating', sa.Integer(), nullable=False),
    sa.Column('before_payload', sa.Text(), nullable=False),
    sa.Column('after_payload', sa.Text(), nullable=False),
    sa.Column('before_due_at', sa.DateTime(), nullable=True),
    sa.Column('after_due_at', sa.DateTime(), nullable=False),
    sa.Column('before_state_version', sa.Integer(), nullable=False),
    sa.Column('after_state_version', sa.Integer(), nullable=False),
    sa.Column('card_content_version', sa.Integer(), nullable=False),
    sa.Column('study_session_id', sa.String(length=32), nullable=True),
    sa.Column('reviewed_at', sa.DateTime(), nullable=False),
    sa.Column('undone_at', sa.DateTime(), nullable=True),
    sa.Column('is_undo_event', sa.Boolean(), nullable=False),
    sa.Column('idempotency_key', sa.String(length=64), nullable=False),
    sa.Column('learning_epoch', sa.Integer(), nullable=False),
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.ForeignKeyConstraint(['card_id'], ['cards.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['srs_state_id'], ['srs_states.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['study_session_id'], ['study_sessions.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'idempotency_key', name='uq_srs_review_idem')
    )
    with op.batch_alter_table('srs_reviews', schema=None) as batch_op:
        batch_op.create_index('ix_srs_reviews_user_time', ['user_id', 'reviewed_at'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    bind = op.get_bind()
    bind.exec_driver_sql('DROP TABLE IF EXISTS search_fts')
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('srs_reviews', schema=None) as batch_op:
        batch_op.drop_index('ix_srs_reviews_user_time')

    op.drop_table('srs_reviews')
    with op.batch_alter_table('user_card_flags', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_card_flags_user_id'))

    op.drop_table('user_card_flags')
    with op.batch_alter_table('study_answers', schema=None) as batch_op:
        batch_op.drop_index('ix_study_answers_session')

    op.drop_table('study_answers')
    with op.batch_alter_table('srs_states', schema=None) as batch_op:
        batch_op.drop_index('ix_srs_states_queue')

    op.drop_table('srs_states')
    with op.batch_alter_table('set_permissions', schema=None) as batch_op:
        batch_op.drop_index('ix_set_permissions_user_set')

    op.drop_table('set_permissions')
    with op.batch_alter_table('card_media', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_card_media_card_id'))

    op.drop_table('card_media')
    with op.batch_alter_table('accepted_answers', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_accepted_answers_card_id'))

    op.drop_table('accepted_answers')
    with op.batch_alter_table('test_attempts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_test_attempts_user_id'))

    op.drop_table('test_attempts')
    with op.batch_alter_table('study_session_items', schema=None) as batch_op:
        batch_op.drop_index('ix_items_session_pos')

    op.drop_table('study_session_items')
    with op.batch_alter_table('srs_enrollments', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_srs_enrollments_user_id'))

    op.drop_table('srs_enrollments')
    with op.batch_alter_table('snapshot_media', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_snapshot_media_study_session_id'))

    op.drop_table('snapshot_media')
    with op.batch_alter_table('share_links', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_share_links_set_id'))

    op.drop_table('share_links')
    with op.batch_alter_table('set_tags', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_set_tags_set_id'))

    op.drop_table('set_tags')
    op.drop_table('search_fallback')
    with op.batch_alter_table('library_entries', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_library_entries_user_id'))

    op.drop_table('library_entries')
    with op.batch_alter_table('import_jobs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_import_jobs_user_id'))
        batch_op.drop_index(batch_op.f('ix_import_jobs_created_at'))

    op.drop_table('import_jobs')
    with op.batch_alter_table('folder_sets', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_folder_sets_folder_id'))

    op.drop_table('folder_sets')
    with op.batch_alter_table('cards', schema=None) as batch_op:
        batch_op.drop_index('ix_cards_set_position')

    op.drop_table('cards')
    op.drop_table('user_preferences')
    op.drop_table('tags')
    with op.batch_alter_table('study_sessions', schema=None) as batch_op:
        batch_op.drop_index('ix_study_sessions_user_status')
        batch_op.drop_index(batch_op.f('ix_study_sessions_last_activity_at'))

    op.drop_table('study_sessions')
    op.drop_table('srs_settings')
    with op.batch_alter_table('sets', schema=None) as batch_op:
        batch_op.drop_index('ix_sets_visibility_updated')
        batch_op.drop_index('ix_sets_owner_updated')
        batch_op.drop_index('ix_sets_archived')

    op.drop_table('sets')
    with op.batch_alter_table('sessions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_sessions_user_id'))
        batch_op.drop_index(batch_op.f('ix_sessions_token_hash'))
        batch_op.drop_index(batch_op.f('ix_sessions_expires_at'))

    op.drop_table('sessions')
    with op.batch_alter_table('media', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_media_owner_id'))

    op.drop_table('media')
    with op.batch_alter_table('match_records', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_match_records_user_id'))

    op.drop_table('match_records')
    op.drop_table('folders')
    op.drop_table('daily_goals')
    with op.batch_alter_table('audit_events', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_audit_events_created_at'))
        batch_op.drop_index(batch_op.f('ix_audit_events_action'))

    op.drop_table('audit_events')
    with op.batch_alter_table('activity_events', schema=None) as batch_op:
        batch_op.drop_index('ix_activity_user_time')
        batch_op.drop_index('ix_activity_user_date')

    op.drop_table('activity_events')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_username_normalized'))

    op.drop_table('users')
    op.drop_table('server_settings')
    # ### end Alembic commands ###
